export const SEND_FORM_REQUEST = 'SEND_FORM_REQUEST';
export const SEND_FORM_SUCESS = 'SEND_FORM_SUCESS';
export const SEND_FORM_FAILURE = 'SEND_FORM_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_UPDATED_SUCCESS';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_CREATED_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
